# Generated by Django 4.0.2 on 2022-03-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='banner',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='brandmodel',
            name='iamge1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='brandmodel',
            name='iamge2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='brandmodel',
            name='iamge3',
            field=models.CharField(default='', max_length=500),
        ),
    ]
