# Generated by Django 4.0.2 on 2022-02-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='seat_count',
            field=models.IntegerField(verbose_name=range(1, 50)),
        ),
    ]
