# Generated by Django 4.0.2 on 2022-02-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='profile',
            new_name='user',
        ),
    ]
