# Generated by Django 4.0.2 on 2022-03-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_brandmodel_banner_brandmodel_iamge1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandmodel',
            old_name='iamge1',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='brandmodel',
            old_name='iamge2',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='brandmodel',
            old_name='iamge3',
            new_name='image3',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='cargo_volume',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_capacity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='height',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='length',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='milage',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='width',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
