# Generated by Django 4.0.2 on 2022-03-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_vehicle_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='creator',
            field=models.CharField(default='bump', max_length=50),
        ),
    ]
