# Generated by Django 4.0.2 on 2022-03-05 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_vehicle_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='creator',
        ),
    ]
