# Generated by Django 4.0.2 on 2022-03-06 02:14

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_vehicle_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Power Steering', 'Power Steering'), ('AC', 'AC'), ('Alarm', 'Alarm'), ('Bluetooth', 'Bluetooth'), ('Heated Seats', 'Heated Seats'), ('Wifi', 'Wifi'), ('Cruise Control', 'Cruise Control'), ('Front Parking Sensor', 'Front Parking Sensor'), ('Rear Parking Sensor', 'Rear Parking Sensor'), ('Roof Rack', 'Roof Rack'), ('Power Window', 'Power Window'), ('Sunroof', 'Sunroof'), ('USB Port', 'USB Port'), ('Sound System', 'Sound System'), ('Memory Seat', 'Memory Seat'), ('Other', 'Other')], default='Other', max_length=178),
        ),
    ]
